### ISSUE TITLE
Reduce for loop function call overhead

### ISSUE THREAD

**Issue by YiranXu** [nyu-cds/xz1757_assignment3#1]
In "nbody" function, the inner for loop "for _ in range(iterations):  advance(0.01, BODIES, key_pairs)" can be moved into "advanced" function by calling  "for _ in range(iterations)" at the beginning of the "advance" function and pass "iterations" as an argument for the "advance" function.

**Comment by nyuxz** [comment]
Thanks, improve a lot.
