### ISSUE TITLE
Put definition of "BODIES" in main function

### ISSUE THREAD

**Issue by YiranXu** [nyu-cds/xz1757_assignment3#2]
It is better to put the definition of "PI", "SOLAR_MASS","DAYS_PER_YEAR","BODIES" in main function rather than "nbody" function.

**Comment by dataframing** [comment]
I actually don't think this will have much of an impact – it just moves those variables from the local namespace to the global. Have you tested to see if it actually changes the performance? Both `main()` and `nbody()` are only called once, so I wouldn't think it has any significant improvement.

**Comment by nyuxz** [comment]
Cool. thanks all of you guys. I tested, Danny is correct. Not to much improvement.
