### ISSUE TITLE
Avoid BODIES.keys() call in advance

### ISSUE THREAD

**Issue by dataframing** [nyu-cds/xz1757_assignment3#3]
The key to improving performance for `nbody_opt.py` is keeping `advance()` as lean and performant as possible. The line:

```python
for body in BODIES.keys():
```

can be improved by doing something like

```python
body_names = BODIES.keys()
```

in `nbody()` and weaving that argument through to `advance()`. This avoids the key lookup which – while marginal for one call – will be significant after `loops * iterations` calls.

**Comment by nyuxz** [comment]
this is cool, thanks.
